<#
.SYNOPSIS
    Creates the directory structure and placeholder files required by Malcolm.
    Run this ONCE before the first "docker compose pull".
#>

$ErrorActionPreference = "Stop"
$base = Join-Path $PSScriptRoot ".."

$dirs = @(
    "opensearch",
    "opensearch-backup",
    "pcap\upload",
    "zeek-logs\upload",
    "zeek-logs\extract_files",
    "zeek\intel",
    "zeek\custom",
    "suricata-logs",
    "suricata\rules",
    "suricata\include-configs",
    "arkime\lua",
    "arkime\rules",
    "logstash\maps",
    "logstash\certs",
    "filebeat\certs",
    "nginx\certs",
    "nginx\auth"
)

Write-Host "Creating Malcolm directory structure..." -ForegroundColor Cyan
foreach ($d in $dirs) {
    $full = Join-Path $base $d
    if (-not (Test-Path $full)) {
        New-Item -ItemType Directory -Path $full -Force | Out-Null
        Write-Host "  Created: $d" -ForegroundColor Green
    } else {
        Write-Host "  Exists:  $d"
    }
}

# Placeholder files required as bind-mount sources so Docker does not create them as directories
$placeholders = @{
    "nginx\nginx_ldap.conf" = "# Malcolm LDAP config placeholder`n"
    "nginx\htpasswd"        = "# Generated by Malcolm auth_setup`n"
    "nginx\certs\dhparam.pem" = "# Run: openssl dhparam -out nginx/certs/dhparam.pem 2048`n"
    "logstash\maps\malcolm_severity.yaml" = "# Malcolm severity map placeholder`n"
}

Write-Host ""
Write-Host "Creating placeholder config files..." -ForegroundColor Cyan
foreach ($kv in $placeholders.GetEnumerator()) {
    $full = Join-Path $base $kv.Key
    if (-not (Test-Path $full)) {
        Set-Content -Path $full -Value $kv.Value -Encoding ASCII
        Write-Host "  Created: $($kv.Key)" -ForegroundColor Green
    } else {
        Write-Host "  Exists:  $($kv.Key)"
    }
}

# Placeholder cert files (Malcolm will regenerate these on first run via auth_setup)
$certPlaceholders = @(
    "logstash\certs\ca.crt",
    "logstash\certs\server.crt",
    "logstash\certs\server.key",
    "filebeat\certs\ca.crt",
    "filebeat\certs\client.crt",
    "filebeat\certs\client.key",
    "nginx\certs\cert.pem",
    "nginx\certs\key.pem"
)

Write-Host ""
Write-Host "Creating placeholder certificate files..." -ForegroundColor Cyan
foreach ($c in $certPlaceholders) {
    $full = Join-Path $base $c
    if (-not (Test-Path $full)) {
        Set-Content -Path $full -Value "# placeholder`n" -Encoding ASCII
        Write-Host "  Created: $c" -ForegroundColor Green
    } else {
        Write-Host "  Exists:  $c"
    }
}

Write-Host ""
Write-Host "Directory init complete." -ForegroundColor Cyan
Write-Host "Next steps:"
Write-Host "  1. Edit .env and change all changeme passwords"
Write-Host "  2. docker compose pull"
Write-Host "  3. docker compose up -d"